[package]
name = "rust-encryption-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
argon2 = "0.5.3"
aes-gcm = "0.10.3"
hmac = "0.12.1"
sha2 = "0.10.8"
getrandom = { version = "0.2.15", features = ["js"] }
